photo_upload/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url (r'^usps/',include('ziplookup.urls')),
)

urlpatterns += patterns('photo_upload.views',
    (r'^$', 'index'),
    (r'^(?P<slug>[\w-]+)/$', 'campaign_render'),
    (r'^(?P<slug>[\w-]+)/upload_raw_photo$', 'upload_raw_photo'), #make sure no trailing slash
    (r'^(?P<slug>[\w-]+)/submit$', 'submit')

)

if settings.DEBUG:
    # quick fix for the fact that my media files are being served by static URL
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

usps/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('usps.views',
    (r'^zip_lookup/{0,1}$', 'zip_lookup'),
)

photo_upload/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage

media = FileSystemStorage()

def example_file_name(instance, filename):
	return "webcam/%s/example.png" % (instance.campaign.slug,instance.pk)
def raw_file_name(instance, filename):
	return "webcam/raw/raw.png"
def captioned_file_name(instance, filename):
	return "webcam/%s/%d_caption.png" % (instance.campaign.slug,instance.pk)

class PhotoCampaign(models.Model):
	title = models.CharField(max_length=50)
	slug = models.SlugField()
	logo = models.ImageField(upload_to='logos/', null=True, blank=True)
	description = models.TextField()
	default_message = models.TextField(null=True,blank=True)
	example_photo = models.ImageField(upload_to=example_file_name,null=True,blank=True)
#	ak_page_name = models.CharField(help_text="name of the page to act on the user",max_length=50,null=True,blank=True)
	
	def __unicode__(self):
		return '%s, %s' % (self.title, self.description,)
	
	def get_title(self):
		return '%s' % self.title
	
	def get_description(self):
		return '%s' % self.description

class RawPhoto(models.Model):
	photo = models.ImageField(upload_to=raw_file_name, storage=media)

	def __unicode__(self):
		return "raw_%s.png" % self.pk

class Photo(models.Model):
	campaign = models.ForeignKey(PhotoCampaign)
	name = models.CharField(max_length=50)
	zip_code = models.CharField(max_length=5)
	email = models.EmailField(max_length=75)
	message = models.CharField(max_length=280,null=True,blank=True)
#	akid = models.PositiveIntegerField(null=True,blank=True)
	raw_photo = models.ForeignKey(RawPhoto, related_name="original_photo")
	captioned_photo = models.ImageField(upload_to=captioned_file_name, storage=media)
	approved = models.BooleanField()

	def final_photo(self):
		return '<img src="/media/%s" width="320" height="240" />' % self.captioned_photo
	final_photo.allow_tags = True
		
	def __unicode__(self):
		return "%s, %s, %s" % (self.name, self.zip_code, self.email,)

photo_upload/forms.py
from django.forms import ModelForm
from django import forms
from models import *

class PhotoForm(ModelForm):
	class Meta:
		model = Photo
		exclude = {'approved',}
		widgets = {
            'message': forms.Textarea(attrs={'cols': 80, 'rows': 20}),
        }
		
class RawPhotoForm(ModelForm):
	class Meta:
		model = RawPhoto

photo_upload/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse,HttpResponseBadRequest,HttpResponseServerError
from django.core.files.base import ContentFile
from django.conf import settings
from django.shortcuts import render
import json

import re
from django.core.files.base import ContentFile
import tempfile

#from ak_support.views import ak_connect,validate_token

from models import *
from forms import *

#TODO:  use os and change directory to parent presente_vote, so that from racewatch.models CampaignPartners 
#can be imported, subsequently allowing us to add partner links into the base template without hardcoding.

    
def index(request):
    campaigns = PhotoCampaign.objects.all()
    return render(request, "list.html", dictionary={'list':campaigns})

def campaign_render(request,slug):
    campaign = get_object_or_404(PhotoCampaign,slug=slug)
    form = PhotoForm(request.POST or None)
    logo = PhotoCampaign.objects.get().logo
    raw_form = RawPhotoForm(request.POST or None)
    context = {}

#    akid = request.GET.get('akid')

#    if akid:
#        ak = ak_connect()
#        user = ak.User.get({'akid':request.GET.get('akid')})
#        if user:
#            context['user'] = user
#            context['recognized'] = True
#        else:
#            context['recognized'] = False

    if form.is_valid():
        new_photo = form.save()

    response_data = {
        'form': form,
    }

    form = PhotoForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        new_upload = form.save()
    else:
        print form.errors

    context = {
        "photos": Photo.objects.filter(campaign=campaign,approved=True),
        'form': form,
        'raw_form': raw_form,
        "campaign": campaign,
        'logo': logo,
    }



    return render(request, "index.html", dictionary=context)
    
@csrf_exempt
def upload_raw_photo(request,slug):
    if request.method == 'POST':
        raw_photo = RawPhoto()
        if request.FILES and request.FILES['photo']:
            raw_content_file = request.FILES['photo']
        else:
            raw_content_file = ContentFile(request.raw_post_data)
        file_name = "raw_photo.png"
        raw_photo.photo.save(file_name, raw_content_file)
        data = {
            'success': True,
            'file_name': file_name,
            'file_url': raw_photo.photo.url,
            'raw_photo_pk': raw_photo.pk
        }
    else:
        data = {'success': False, 'message':"must post to this url"}
    return HttpResponse(json.dumps(data),mimetype="text/html")
    
@csrf_exempt
def submit(request,slug):
    required_fields = ['name','zip_code','email','captioned_photo','raw_photo_id']
    for f in required_fields:
        if request.POST.get(f) == "":
            resp = {'message':'%s is required' % f,
                    'field':f}
            return HttpResponseBadRequest(json.dumps(resp),mimetype="application/json")

    #decode the dataurl
    dataurl = request.POST['captioned_photo']
    encoded_photo = re.search(r'base64,(.*)', dataurl).group(1)
    decoded_photo = encoded_photo.decode('base64')

    #save it to a ContentFile
    captioned_content_file = ContentFile(decoded_photo)
    captioned_file_name = "test_upload.png"

	#create the django photo object
    try:
        campaign = PhotoCampaign.objects.get(slug=slug)
        raw_photo = RawPhoto.objects.get(id=request.POST.get('raw_photo_pk'))
    except PhotoCampaign.DoesNotExist:
        resp = {'message':'no such campaign %s' % slug}
        return HttpResponseServerError(json.dumps(resp),mimetype="application/json")

    except RawPhoto.DoesNotExist:
        resp = {'message':'raw photo upload failed','field':""}
        return HttpResponseServerError(json.dumps(resp),mimetype="application/json")

    new_photo = Photo.objects.create(name=request.POST.get('name'),
                                    zip_code=request.POST.get('zip_code'),
                                    email=request.POST.get('email'),
                                    message = request.POST.get('message'),
                                    campaign=campaign,
                                    raw_photo=raw_photo,)
                                    #akid=request.POST.get('akid'))
    try:
        new_photo.captioned_photo.save(captioned_file_name,captioned_content_file)
#        if new_photo.akid:
#           new_photo.approved = True
        new_photo.save()
        resp = {'message':'success'}
    except Exception:
        resp = {"message":"error"}

#
#    if new_photo.campaign.ak_page_name:
#        #now act on the user
#        ak = ak_connect()
#        act_dict = {'email': new_photo.email,
#                    'postal':new_photo.zip_code,
#                    'page': new_photo.campaign.ak_page_name}
#        if not new_photo.akid:
#            act_dict['name'] = new_photo.name
#        else:
#            pass
#            #because we are shortening the displayed name for recognized users
#            #don't want to overwrite good data with bad
#
#        #some issues with Python 2.7 and xmlrpc... I am not adept enough at Python to know what to fix here, sadly.
#   
#        ak.act(act_dict)


    return HttpResponse(json.dumps(resp),mimetype="application/json")

photo_upload/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Upload</title>
	<meta name="description" content="A tool for engaging people to upload photos.">

	<meta name="viewport" content="width=device-width">

	<link rel="stylesheet" href="{{STATIC_URL}}css/style.css" />
	<!--[if IE]><link rel="stylesheet" href="{{STATIC_URL}}css/fileuploader.css" /><![endif]-->

	{%block extra_head%}{%endblock%}

	<script src="{{STATIC_URL}}js/libs/modernizr-2.5.3.min.js"></script>
</head>

<body>
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->


		{%block content%}{%endblock%}



	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
	<script>window.jQuery || document.write('<script src="{{STATIC_URL}}js/libs/jquery-1.7.1.min.js"><\/script>')</script>



	{%block extra_script%}
	{%endblock%}
	<script>
		var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
</body>
</html>

photo_upload/templates/index.html
{% extends "base.html" %}


{%block content%}
<div id="black_overlay"></div>
<div class="flashDiv"></div>
<div id="wrapper">
<ul id="photo_grid">
	{{raw_post}}
		<li class="captioned_photo first">
		<h2>{{campaign.title}}</h2>
		<p>{{campaign.description}}</p>
		<div id="start_upload">
			<button>Upload</button>
		</div>
		</li>
	{%for photo in photos%}
		<li class="captioned_photo"><img class="lazy" src="{{STATIC_URL}}/img/grey.gif" data-original="{{MEDIA_URL}}{{photo.captioned_photo}}" /></li>
	{%endfor%}
</ul>



<div id="upload">
	<article id="step-1">
		<section class="left-section">
			<h2>Use your webcam to take a photo!</h2>
			<ol>
				<li>Click &#10004; to allow camera access &rarr;</li>
				<li>Smile for the camera <span>&#9786;</span></li>
				<li>Click the button &darr;</li`>
			</ol>
			<button id="snap-button">Take Photo</button>
			<p>No webcam?  Upload a photo!</p>
			<div id="file-uploader"></div> 
			<form id="upload_photo" method="POST" action="upload_raw_photo" enctype="multipart/form-data">
				{{raw_form.as_ul}}
				<input id="uploadDirect" type="submit" value="Upload your photo!" />
			</form>
			<a id="helpTextLink" href="#helpText">Can't click on the "allow" button?</a>
				<div id="helpText"><span>This seems to be a problem with Flash Player and is currently beyond our control. Please try the following to fix:</span>
				<ol>
					<li>Go to the <a href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager06.html">Flash Player settings website</a></li>
					<li>Under the Website Privacy Settings tab, find nuestraeleccion.org in the privacy settings in the "Visited Websites" list.</li>
					<li>Click on nuestraeleccion.org to highlight it, and then select the "Always allow" option above.</li>
					<li>Close the flash settings web page to save, restart your web browser, and try again.</li>
				</ol>	
				</div>
		</section>
		<section class="right-section">
			<div id="camera"></div>
		</section>
	</article>
		
	<article id ="step-2">
		<section class="left-section">
			<form id="caption_form" action="/submit" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<!-- csrf token ajax for photo, pass to PhotoUpload view -->
				{{ form.non_field_errors }}
				<div class="nophoto">
				    <div class="fieldWrapper">
				        {{form.captioned_photo.errors}}
				        <label for="id_captioned_photo">Upload a photo</label>
				        {{form.captioned_photo}}
				       </div>		
				   </div>	
				   <div id="captioned_photo" class="fieldWrapper">
					{{ form.captioned_photo.errors }}
				</div>
				{% if recognized %}
					Not {{user.first_name}} {{user.last_name}}? <a href=".">click here</a>
					<input id="id_name" type="hidden" name="name" value="{{user.first_name}} {{user.last_name|slice:'1'}}" />
					<input id="id_zip_code" type="hidden" name="zip_code" value="{{user.postal}}" />
					<input id="id_email" type="hidden" name="email" value="{{user.email}}" />
					<input id="id_akid" name="akid" type="hidden" value="{{user.id}}"/>
				{%else%}
					<div class="fieldWrapper">
						<label for="id_name">Your Name</label>
						<input id="id_name" type="text" name="name" maxlength="50" />
					</div>
					<div class="fieldWrapper">
					    <label for="id_zip_code">Your zip code</label>
					    <input id="id_zip_code" type="text" name="zip_code" maxlength="5" />
					</div>
					<div class="fieldWrapper">
					    <label for="id_email">Your email</label>
					    <input id="id_email" type="text" name="email" maxlength="75" />
					</div>
				{%endif%}
				 <div class="fieldWrapper">
					<label for="id_message">Your Message: <span></span></label>
					<textarea id="id_message" rows="10" cols="40" maxlength="140" name="message">{{campaign.default_message}}</textarea>
				</div>
				<input id="id_raw_photo_url" name="raw_photo_url" type="hidden" />
				<input id="id_raw_photo_pk" name="raw_photo_pk" type="hidden" />
				<a id="clearFields" href="#" />Clear</a>
				<a id="startOver" href="#" />Start Over</a>
				<input id="sendForm" type="submit" value="Submit" />
				<a href="#privacy">privacy policy</a>
              	<div id="privacyText">
                <p>
                  “You will receive updates from Presente.org as a result of submitting your email. You will be able to unsubscribe from our list at any time. Presente.org won’t share your information with anyone else without your consent.”
                </p>
              </div>
			</form>	
		</section>
		<section class="right-section">
			<canvas id="canvas-foreground" width="640" height="480"></canvas>
			<canvas id="canvas" width="640" height="480"></canvas>
		</section>
	</article>
</div>

</div>

<div class="push"></div>
{%endblock%}

{%block extra_script%}




<script type="text/javascript">
//passing the logo to our Javascript from our photo object - might be a more proper way to do this?
var logo_url = "{{MEDIA_URL}}{{logo}}";
</script>

<script src="{{STATIC_URL}}js/spin.min.js"></script>
<script src="{{STATIC_URL}}js/jquery.lazyload.min.js"></script>
<script src="{{STATIC_URL}}js/webcam.js"></script>
<script src="{{STATIC_URL}}js/main.js"></script>

<!--[if lt IE 9]>
	<script src="{{STATIC_URL}}js/flashcanvas.js"></script>
<![endif]-->

<!--[if IE]>
	<script src="{{STATIC_URL}}js/fileuploader.js"></script>
	<script src="{{STATIC_URL}}js/photo_upload_ie.js"></script>
<![endif]-->
{%endblock%}

photo_upload/templates/list.html
{% extends "base.html" %}

{%block content%}
<h2>List of currently active photo campaigns</h2>
<ul>
	{% for c in list%}
		<li><a href='/{{c.slug}}'>{{c.title}}</a></li>
	{%endfor%}
</ul>

{%endblock%}